<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emfguava" nsURI="https://github.com/felixdo/emf-guava" nsPrefix="emfguava">
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" instanceClassName="com.google.common.base.Predicate"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" instanceClassName="com.google.common.base.Function"
      abstract="true" interface="true">
    <eTypeParameters name="F"/>
    <eTypeParameters name="T"/>
  </eClassifiers>
</ecore:EPackage>
